apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: lab-spring-boot-k8s-gs
spec:
  vendor: eduk8s.io
  title: (NOT FUNCTIONAL) Getting Started with Spring Boot on Kubernetes
  description: Create your first Spring Boot application and deploy it to Kubernetes
  url: https://github.com/eduk8s-labs/lab-spring-boot-k8s-getting-started
  duration: 15m
  content: 
    image: quay.io/eduk8s/jdk11-environment:master
    files: github.com/eduk8s-labs/lab-spring-boot-k8s-getting-started
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true