apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: lab-spring-boot-k8s-gs
spec:
  vendor: vmware.com
  title: Getting Started with Spring Boot on Kubernetes
  description: Create your first Spring Boot application and deploy it to Kubernetes
  url: https://github.com/tanzu-end-to-end/lab-spring-boot-k8s-getting-started
  duration: 15m
  content: 
    image: gcr.io/pa-cdelashmutt/tanzu-e2e/learning-center-jdk17-environment:latest
    files: github.com/tanzu-end-to-end/lab-spring-boot-k8s-getting-started
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true