#@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-overview
spec:
  content:
    files: github.com/tanzu-end-to-end/tap-workshop?ref=main
    image: harbor.tap.corby.cc/tanzu-e2e/eduk8s-tap-workshop:latest
  description: An introduction to the Tanzu Application Platform
  difficulty: beginner
  duration: 30m
  session:
    applications:
      console:
        enabled: true
      registry:
        enabled: true
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
    env:
    - name: GITEA_PASSWORD
      value: #@ data.values.gitea.adminPassword
    - name: HARBOR_USER
      value: #@ data.values.harbor.user
    - name: HARBOR_PASSWORD
      value: #@ data.values.harbor.adminPassword
    - name: VIEW_CLUSTER_DOMAIN
      value: contour.e2e.corby.cc
    namespaces:
      budget: custom
    objects:
    - apiVersion: v1
      kind: LimitRange
      metadata:
        name: resource-limits
      spec:
        limits:
        - max:
            storage: 10Gi
          type: PersistentVolumeClaim
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-workshop-read-crb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: k8s-reader
      subjects:
      - kind: ServiceAccount
        name: $(service_account)
        namespace: $(workshop_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-workshop-rw-crb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: workshop-cluster-role
      subjects:
      - kind: ServiceAccount
        name: $(service_account)
        namespace: $(workshop_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-session-read-crb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: k8s-reader
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: $(session_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-session-rw-crb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: workshop-cluster-role
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: $(session_namespace)
    resources:
      memory: 2Gi
  title: (NOT FUNCTIONAL) TAP Overview
  url: https://github.com/tanzu-end-to-end/tap-workshop
  vendor: eduk8s.io
