#@ load("@ytt:data", "data")
---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: waas-mvp
spec:
  title: WaaS MVP
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Tanzu-Solutions-Engineering/WaaS-MVP
  content:
    #!image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/Tanzu-Solutions-Engineering/WaaS-MVP?ref=main
  session:
    env:
    - name: HARBOR_PASSWORD
      value: #@ data.values.harbor.adminPassword
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: e2e-user
      rules:
      - apiGroups: [ e2e.tanzu.vmware.com ]
        resources: [ "*" ]
        verbs: [ get, list, watch, create, delete, patch, update ]
      - apiGroups: [ "*" ]
        resources: [ "*" ]
        verbs: [ get, list, watch ]
      - apiGroups: [""]
        resources: [ events ]
        verbs: [ create ]
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: e2e-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: e2e-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: e2e.tanzu.vmware.com/v1beta1
      kind: HarborProject
      metadata:
        name: $(session_namespace)
        annotations:
          training.eduk8s.io/objects.crd.scope: Namespaced
      spec:
        name: $(session_namespace)

