#@ load("value-secret.lib.txt", "values_file")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: waas-catalog-values
  namespace: packages
data:
  values.yaml: #@ base64.encode(values_file())